name: Release

on:
  push:
    tags:
      - 'v*'        # v1.0.0 などタグを押したら実行

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            args: ''                       # Windows x64
          - os: macos-latest
            args: ''                       # macOS (Intel/Apple 両対応は自動検出)

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write                      # Release 作成権限

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # フロントエンド依存をサブフォルダでインストール
      - name: Install frontend deps
        run: npm ci --prefix suiperchat_streamer_app

      # Npcap SDK インストールステップに ID を追加し、出力変数を設定
      - name: Install Npcap SDK (Windows)
        id: install_npcap # ★ ID を追加
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # 1. SDK のバージョンと URL を設定
          $npcap_sdk_version = "1.15"
          $npcap_sdk_url     = "https://npcap.com/dist/npcap-sdk-$($npcap_sdk_version).zip"
          
          # 2. ダウンロード
          Write-Host "Downloading Npcap SDK version $npcap_sdk_version from $npcap_sdk_url"
          curl -L -o npcap-sdk.zip $npcap_sdk_url
          
          # 3. 展開
          Write-Host "Extracting Npcap SDK"
          Expand-Archive npcap-sdk.zip -DestinationPath .
          
          # 4. Lib/x64 フォルダへのパスを取得 (Join-Path を使用)
          $npcap_sdk_path = Join-Path (Get-Location).Path "npcap-sdk-$npcap_sdk_version\Lib\x64"
          Write-Host "Npcap SDK Lib path: $npcap_sdk_path"
          
          # 現在の LIB に SDK パスを追加
          echo "LIB=$env:LIB;$npcap_sdk_path" >> $env:GITHUB_ENV

      - name: Debug LIB (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "===== LIB variable dump ====="
          $env:LIB -split ';' | ForEach-Object { Write-Host $_ }

      - name: Cargo verbose build (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          # 1) Tauri/Cargo プロジェクトルートへ移動
          cd suiperchat_streamer_app/src-tauri

          # 2) RUSTFLAGS を設定してビルド（--verbose でリンク引数を全部表示）
          echo ">>> Running cargo build with link verbosity"
          RUSTFLAGS="-C link-arg=/VERBOSE" cargo build --release --verbose || true

      # ★ tauri-action ★
      # tauri-action ステップで LIB 環境変数を設定
      - uses: tauri-apps/tauri-action@v0
        id: tauri_build # 必要であれば ID を追加
        with:
          projectPath: suiperchat_streamer_app  # ← Tauri プロジェクトの場所
          tagName: ${{ github.ref_name }}       # 例: v1.0.0
          releaseDraft: false                   # 直接公開
          releaseName: ${{ github.ref_name }}   # リリース名を明示的に設定
          includeUpdaterJson: true              # latest.json を自動生成
          args: ${{ matrix.args }}
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}