name: Release

on:
  push:
    tags:
      - 'v*'  # v1.0.0 などのタグをトリガーに

jobs:
  build-and-publish:
    # (1) run: ステップをサブフォルダ内で動かす
    defaults:
      run:
        working-directory: suiperchat_streamer_app

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04   # Linux ビルド
            args: ''
          - os: windows-latest # Windows ビルド
            args: ''
          - os: macos-latest   # macOS ビルド
            args: ''

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write      # Release 作成に必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install frontend dependencies
        run: npm ci

      - name: Install Linux build dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev patchelf

      - name: Build & publish with Tauri Action
        uses: tauri-apps/tauri-action@v2
        with:
          # (2) Tauri のルートをカレントディレクトリとする
          projectPath: '.'
          tagName: ${{ github.ref_name }}
          releaseDraft: false
          includeUpdaterJson: true
          updaterJsonPreferNsis: false
          updaterJsonKeepUniversal: false
          args: ${{ matrix.args }}
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Verify release assets
        run: echo "Release completed on ${{ matrix.os }}"
