name: Release

on:
  push:
    tags:
      - 'v*'        # v1.0.0 などタグ Push 時に実行

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest    # Windows x64
            args: ''
          - os: macos-latest      # macOS (Apple/Intel 両対応)
            args: ''

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write             # Release 作成権限

    steps:
      # コードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v3

      # Node.js セットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Rust ツールチェインセットアップ
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # フロントエンド依存インストール
      - name: Install frontend deps
        run: npm ci --prefix suiperchat_streamer_app

      # Tauri ビルド & GitHub Release
      - name: Build & Release
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath:        suiperchat_streamer_app
          tagName:            ${{ github.ref_name }}
          releaseName:        ${{ github.ref_name }}
          releaseDraft:       true
          includeUpdaterJson: true
        env:
          GITHUB_TOKEN:                       ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY:          ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          NPCAP_LIB_PATH:                     ${{ github.workspace }}/suiperchat_streamer_app/src-tauri/npcap_sdk
