name: Release

on:
  push:
    tags:
      - 'v*'        # v1.0.0 などタグを押したら実行

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            args: ''                       # Linux x64
          - os: windows-latest
            args: ''                       # Windows x64
          - os: macos-latest
            args: ''                       # macOS (Intel/Apple 両対応は自動検出)

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write                      # Release 作成権限

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # フロントエンド依存をサブフォルダでインストール
      - name: Install frontend deps
        run: npm ci --prefix suiperchat_streamer_app

      # Linux だけ追加ライブラリを入れる
      - name: Linux deps
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev patchelf

      # ★ tauri-action ★
      - uses: tauri-apps/tauri-action@v0        # ← v0 系を指定
        with:
          projectPath: suiperchat_streamer_app  # ← Tauri プロジェクトの場所
          tagName: ${{ github.ref_name }}       # 例: v1.0.0
          releaseDraft: false                   # 直接公開
          releaseName: ${{ github.ref_name }}   # リリース名を明示的に設定
          includeUpdaterJson: true              # latest.json を自動生成
          args: ${{ matrix.args }}
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
